export const quotes = [
    "Everything is hard before it is easy. – Goethe",
    "If you change the way you look at things, the things you look at change. – Wayne Dyer",
    "Everyone thinks of changing the world, but no one thinks of changing himself. – Leo Tolstoy",
    "I choose to make the rest of my life the best of my life. – Louise Hay",
    "You just can’t beat the person that never gives up. – Babe Ruth",
    "Great things are done by a series of small things brought together. – Vincent Van Gogh",
    "If there is no struggle, there is no progress. – Frederick Douglass",
    "All great change in America begins at the dinner table. – Ronald Reagan",
    "How wonderful is it that nobody need wait a single moment before starting to improve the world. – Anne Frank",
    "Sometimes when you’re in a dark place you think you’ve been buried but you’ve actually been planted. – Christine Caine",
    "Memory…is the diary that we all carry about with us. – Oscar Wilde",
    "The best gift anyone can give, I believe, is the gift of sharing themselves. – Oprah Winfrey",
    "In order to be irreplaceable, one must always be different. – Coco Chanel",
    "Make each day your masterpiece. – John Wooden",
    "The world is but a canvas to our imagination. – Henry David Thoreau",
    "Doubt kills more dreams than failure ever will. – Suzy Kassem",
    "The idea is to write it so that people hear it and it slides through the brain and goes straight to the heart. – Maya Angelou",
    "I want to put a ding in the universe. – Steve Jobs",
    "Honesty is the first chapter in the book of wisdom. – Thomas Jefferson",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "I like to skate to where the puck is going to be, not where it has been. – Wayne Gretzky",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "Today is your opportunity to build the tomorrow you want. – Ken Poirot",
    "If you tell the truth, you don’t have to remember anything. – Mark Twain",
    "If you think you’re too small to make a difference, try sleeping with a mosquito. – Dalai Lama",
    "Be so good they can’t ignore you. – Steve Martin",
    "The world breaks everyone, and afterward, some are strong at the broken places. – Ernest Hemingway"
];